# Generated by Django 5.0.7 on 2024-07-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_conges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacances'), ('sick', 'Maladie'), ('unpaid', 'Sans solde')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
