# Generated by Django 3.2.25 on 2024-08-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_conges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_type',
        ),
    ]
