# Generated by Django 3.2.25 on 2024-08-07 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_conges', '0004_department_performance_training'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='gestion_conges_department',
        ),
    ]
