# Generated by Django 3.2.25 on 2024-07-30 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_conges', '0005_alter_employee_first_name_alter_employee_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='gestion_conges.employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(),
        ),
    ]
